/// Flutter icons UpNewsIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UpNewsIcons
///      fonts:
///       - asset: fonts/UpNewsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UpNewsIcons {
  UpNewsIcons._();

  static const _kFontFam = 'UpNewsIcons';

  static const IconData ic_email = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_facebook = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_google = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ic_interest = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ic_send = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ic_star = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData ic_account = const IconData(0xe806, fontFamily: _kFontFam);
}
